apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    password: AgDLNx9hWq7v7WYrs6tOjs6IB4RhWdMhQTYQpcJqCJlM7Psast8Y2bFW1bvBlsfLc2EXTfmtK5dN+t+G4TcqbtW6wWTGC78zrVuHiMyeOsMCPzxI5KlLMdEZK0NrB6WYcIS/iP3XH44wn4ONoJjXB1lUNLLmzN4xy1l9/G7Jy+tohd6E0CTv+V8Nk6UOpIxyQbwI+R9z4c303RpvZIG0aDgn+Jm3lGqCvkEheIF6WLLmeUl4LzwNthUhasoSkDewhEb2rveTBN/TfHAiuGSR5buE8EQRVyzZAlyKN/Unwub93Fjzqh+pWxSk1GK5PXe3nb1WlUb44/mbNvwrlQZK6mehKccD+grDyYUkbOqcqcC/WJVotChydE4tkFu+YVeQiaH6rH4rOTqayBs5s7cCPd1tfmWOMsFACKHSlU2lMeiYXB4kiPD0d07vvGTCmQ2QR91Hq1bfJFHLJsOATzqeuPnOsvKjKdKKdxWV1RVSWYCHdnh4P15p4Qcsn9A34qK+mGywKD23Ps+gR07Ayg14YZEgXnuwXHLWti4/NYrd7YegzmlzjaezgM3aDFpz2WwnO/ceJMQG6J5o2WfOvAECwT6C/oUp6yOcfnMDBL1fZN0D98JGF0Q9AhHfM7KLrvHWW1clK9yooesiuysZWg0uwd0UCgxN38cWiVnJZ4QferMEOb3w/rbyzg05+bzfHekrNmOeUu0=
    username: AgB5VxIe4IpRAzx6nUN6DgapBU88oKFISafU3WIqaUv0bmAnay7L90KmmBVd9klwBnvYXoBXiiLuna0ozKA5MlG3ZanParJ1x9V9Hy2n4n5ggYrHfCesfIRK6ga0VRvJxK4LL6sX3CpO9ERdmy63Lpe7cSztj2iOWzJLHVpweTSAFONTCYtr/2D99tRBAhR7hwPzMF3JD8I1sp4swmdjiT9/aBrg0yt2/cGIYGy8iOxfAUoX1ou1Y2QVqkEIxB/LY0pELcOVEeKWTp3wYovMsv9n3AD64BMgJ/D7M+QxDW1kUz53xwlIypJs9tSnVmvFcOxL8qGmjcCfSzdMMEFrpeG8fPacNEklA+Jv4VYsIOHVUVYQJsD1rjBQAdsbgrUjvOPG4lZGh1K9NR+P0qzm2won1gpQaGkna/AD0AIaewwS+//44DfXjJKPtYIVSeklE7mnFV/sCaHFvrj7L4/evHPP/b02EL1Dx5jPKOSQdiXTq3uG7aG+KdEOq9ztRmf4rvdSb/QAoWbTgh3h3LrIJWEw+aHER6hf4QNtaUG6dDdteRYTfB9SFFH20LtGwJQAcGtHc/VkCmT3Bn5fkLf/t9Xrs7l8DLnKAKf8X/vsbVKdmOLyRV38ln1Uttjp0mvriXpLfLfMyYwCK9qSU5vG7UcFI0LBppJTzHJzImxDX/RIMTeWrm+bCDo9pSsaYbD4dJ+eyPznLw==
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default

